apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: frontend  
  name: catalog-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog  
    spec:
      containers:
      - name: catalog-con
        image: golang:1.15-alpine #gcr.io/formationgcp-baptiste/github.com/jamykun/pfr-product@sha256:15f3a512ece593f2b8b92d64fb1540dc90a0b7e5bd605b900cc9f2c145123410
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        ports:
        - containerPort: 3550
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: catalog-svc
spec:
  selector:
    app: catalog
  ports:
  - port: 3550
    targetPort: 3550
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: frontend
  name: catalog-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
